---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: always
  image: smearieryeti/docker-build
  settings:
    repo: fivem-dev

- name: publish
  pull: always
  image: smearieryeti/docker-publish
  settings:
    from: fivem-dev
    repo: spritsail/fivem
    tags:
    - latest
    - "%label org.label-schema.version"
  environment:
    DOCKER_PASSWORD:
      from_secret: docker_password
    DOCKER_USERNAME:
      from_secret: docker_username
  when:
    branch:
    - master
    event:
    - push
    - tag

- name: notify
  pull: always
  image: smearieryeti/notify
  environment:
    NOTIFY_TOKEN:
      from_secret: notify_token
    WEBHOOK_URL:
      from_secret: webhook_url
  when:
    status:
    - success
    - failure

---
kind: signature
hmac: 30bc93aa03d828dba810f061bc334d78649ad0afd9d07f356906829d79255cf3

...
